# Generated by Django 4.2.25 on 2025-10-27 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('chef_equipe', models.CharField(max_length=100)),
                ('projet_en_cours', models.CharField(blank=True, max_length=150, null=True)),
                ('date_creation', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
