# Generated by Django 4.2.25 on 2025-10-27 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipe',
            name='franchise',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
