# Generated by Django 4.2.25 on 2025-10-27 10:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('equipe', '0002_equipe_franchise'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_commande', models.CharField(max_length=50)),
                ('client', models.CharField(max_length=100)),
                ('date_commande', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Affectation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_menuiseries', models.PositiveIntegerField(default=0)),
                ('date_affectation', models.DateField(default=django.utils.timezone.now)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipe.commande')),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipe.equipe')),
            ],
        ),
    ]
