# Generated by Django 4.2.25 on 2025-10-27 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipe', '0003_commande_affectation'),
    ]

    operations = [
        migrations.AddField(
            model_name='affectation',
            name='franchise',
            field=models.CharField(choices=[('Alger', 'Alger'), ('Trari', 'Oran'), ('Constantine', 'Constantine'), ('Annaba', 'Annaba'), ('Blida', 'Blida')], default='Trari', max_length=100),
        ),
        migrations.AlterField(
            model_name='affectation',
            name='commande',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='equipe',
            name='franchise',
            field=models.CharField(choices=[('Alger', 'Alger'), ('Trari', 'Oran'), ('Constantine', 'Constantine'), ('Annaba', 'Annaba'), ('Blida', 'Blida')], default='Trari', max_length=100),
        ),
    ]
