# Generated by Django 4.2.25 on 2025-10-27 12:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('equipe', '0004_affectation_franchise_alter_affectation_commande_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affectation',
            name='franchise',
            field=models.CharField(choices=[('Alger', 'Sahraoui'), ('Oran', 'Trari'), ('Constantine', 'Constantine'), ('Annaba', 'Kerassa'), ('Blida', 'Mouhoubi')], default='Trari', max_length=100),
        ),
        migrations.AlterField(
            model_name='equipe',
            name='franchise',
            field=models.CharField(choices=[('Alger', 'Sahraoui'), ('Oran', 'Trari'), ('Constantine', 'Constantine'), ('Annaba', 'Kerassa'), ('Blida', 'Mouhoubi')], default='Trari', max_length=100),
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_evaluation', models.DateField(default=django.utils.timezone.now)),
                ('ponctualite', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='Note de 1 à 5')),
                ('qualite_travail', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='Note de 1 à 5')),
                ('respect_client', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='Note de 1 à 5')),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('affectation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipe.affectation')),
            ],
        ),
    ]
